repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/semgrep/pre-commit
    rev: 'v1.175.0'
    hooks:
      - id: semgrep
        args: ['--config', 'auto', '--error']
